// Generated by https://quicktype.io

export interface ValidateTokenResponse {
  href: string;
  status: boolean;
  message: string;
  data: Data;
  statusCode: string;
  errors: object;
  self: object;
}

export interface Data {
  id: number;
  email: string;
  fullName: string;
  firstName: string;
  lastName: string;
  token: string;
  phoneNumber: string;
  zebrraId: string;
}
